/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AwardTableComp: typeof import('./src/components/PersonCenterComp/AwardTableComp.vue')['default']
    ElAvatar: typeof import('element-plus/es')['ElAvatar']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCol: typeof import('element-plus/es')['ElCol']
    ElContainer: typeof import('element-plus/es')['ElContainer']
    ElDatePicker: typeof import('element-plus/es')['ElDatePicker']
    ElDialog: typeof import('element-plus/es')['ElDialog']
    ElDivider: typeof import('element-plus/es')['ElDivider']
    ElDropdown: typeof import('element-plus/es')['ElDropdown']
    ElDropdownItem: typeof import('element-plus/es')['ElDropdownItem']
    ElDropdownMenu: typeof import('element-plus/es')['ElDropdownMenu']
    ElEmpty: typeof import('element-plus/es')['ElEmpty']
    ElFooter: typeof import('element-plus/es')['ElFooter']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElHeader: typeof import('element-plus/es')['ElHeader']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElInputNumber: typeof import('element-plus/es')['ElInputNumber']
    ElLink: typeof import('element-plus/es')['ElLink']
    ElMenu: typeof import('element-plus/es')['ElMenu']
    ElMenuItem: typeof import('element-plus/es')['ElMenuItem']
    ElPageHeader: typeof import('element-plus/es')['ElPageHeader']
    ElPagination: typeof import('element-plus/es')['ElPagination']
    ElRadio: typeof import('element-plus/es')['ElRadio']
    ElRadioGroup: typeof import('element-plus/es')['ElRadioGroup']
    ElRow: typeof import('element-plus/es')['ElRow']
    ElScrollbar: typeof import('element-plus/es')['ElScrollbar']
    ElSwitch: typeof import('element-plus/es')['ElSwitch']
    ElTable: typeof import('element-plus/es')['ElTable']
    ElTableColumn: typeof import('element-plus/es')['ElTableColumn']
    ElTag: typeof import('element-plus/es')['ElTag']
    ElUpload: typeof import('element-plus/es')['ElUpload']
    FootBarComp: typeof import('./src/components/BarComp/FootBarComp.vue')['default']
    MatchCardComp: typeof import('./src/components/MatchManageComp/MatchCardComp.vue')['default']
    MatchTableComp: typeof import('./src/components/MatchManageComp/MatchTableComp.vue')['default']
    NoticeCardComp: typeof import('./src/components/HomeComp/NoticeCardComp.vue')['default']
    PostEditorComp: typeof import('./src/components/PostComp/PostEditorComp.vue')['default']
    PostListComp: typeof import('./src/components/PostComp/PostListComp.vue')['default']
    PostTableComp: typeof import('./src/components/PostManageComp/PostTableComp.vue')['default']
    ReasonCardComp: typeof import('./src/components/HomeComp/ReasonCardComp.vue')['default']
    RecentMatchCard: typeof import('./src/components/HomeComp/RecentMatchCard.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SideBarComp: typeof import('./src/components/BarComp/SideBarComp.vue')['default']
    TopBarComp: typeof import('./src/components/BarComp/TopBarComp.vue')['default']
    TopBarRightComp: typeof import('./src/components/BarComp/BarItemComp/TopBarRightComp.vue')['default']
    UserCardComp: typeof import('./src/components/PersonCenterComp/UserCardComp.vue')['default']
    UserTableComp: typeof import('./src/components/UserManageComp/UserTableComp.vue')['default']
  }
  export interface ComponentCustomProperties {
    vLoading: typeof import('element-plus/es')['ElLoadingDirective']
  }
}
